name: CMake for MacOS

on:
  push:
    branches: [ main ]
  
env:
  # the directory of the library's source code (and which contains the CMakeLists.txt)
  TFM_DIR: /Users/runner/work/test-for-mac/test-for-mac/tfm
  # directories of the different builds
  REL_DIR: ${{github.workspace}}/macos-build-release
  DEB_DIR: ${{github.workspace}}/macos-build-debug
  # compilers
  C: /usr/local/Cellar/gcc/11.2.0_3/bin/gcc-11
  CXX: /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11
  
jobs:
  macos_build:
    runs-on: macos-latest

    steps:
    - name: Download library
      uses: actions/checkout@v2

    - name: Configure CMake on MacOS
      run: |
        echo "env.TFM_DIR: ${{env.TFM_DIR}}" |
        echo "env.REL_DIR: ${{env.REL_DIR}}" |
        cmake ${{env.TFM_DIR}} -B ${{env.REL_DIR}} -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{env.C}} -DCMAKE_CXX_COMPILER=${{env.CXX}} #;
        #cmake ${{env.TFM_DIR}} -B ${{env.DEB_DIR}} -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=${{env.C}} -DCMAKE_CXX_COMPILER=${{env.CXX}}

    - name: Build on MacOS
      run: cmake --build ${{env.REL_DIR}} --config Release VERBOSE=1 -j4 #;
           #cmake --build ${{env.DEB_DIR}} --config Debug -j4

    - name: Upload compiled library
      uses: actions/upload-artifact@v2
      with:
        name: compilation-for-macos
        path: |
          ${{env.REL_DIR}}/libtfm.so*
       # ${{env.DEB_DIR}}/libtfmdebug.so*
