name: CMake for MacOS

on:
  push:
    branches: [ main ]
  
env:
  # the directory of the library's source code (and which contains the CMakeLists.txt)
  TFM_DIR: /Users/runner/work/test-for-mac/test-for-mac/tfm
  # directories of the different builds
  REL_DIR: ${{github.workspace}}/macos-build-release
  DEB_DIR: ${{github.workspace}}/macos-build-debug
  CLANG_LLVM: /usr/local/opt/llvm/bin/clang
  CLANGXX_LLVM: /usr/local/opt/llvm/bin/clang++
  
jobs:
  macos_build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    #- name: Install basic libraries that should already be there
    #  run: brew install libomp
    
    - name: Configure CMake on MacOS
      run: cmake ${{env.TFM_DIR}} -B ${{env.REL_DIR}} -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{CLANG_LLVM}} -DCMAKE_CXX_COMPILER=${{CLANGXX_LLVM}} ;
           cmake ${{env.TFM_DIR}} -B ${{env.DEB_DIR}} -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=${{CLANG_LLVM}} -DCMAKE_CXX_COMPILER=${{CLANGXX_LLVM}}

    - name: Build on MacOS
      run: cmake --build ${{env.REL_DIR}} --config Release -j4;
           cmake --build ${{env.DEB_DIR}} --config Debug -j4

    - uses: actions/upload-artifact@v2
      with:
        name: compilation-for-macos
        path: |
          ${{env.REL_DIR}}/libtfm.so*
          ${{env.DEB_DIR}}/libtfmdebug.so*
