name: CMake for MacOS

on:
  push:
    branches: [ main ]
  
env:
  # the directory of the library's source code (and which contains the CMakeLists.txt)
  TFM_DIR: /home/runner/work/test-for-mac/test-for-mac/tfm
  # directories of the different builds
  REL_DIR: ${{github.workspace}}/macos-build-release
  DEB_DIR: ${{github.workspace}}/macos-build-debug
  
jobs:
  ubuntu_build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure CMake on MacOS
      run: ls ;
           cmake ${{env.TFM_DIR}} -B ${{env.REL_DIR}} -DCMAKE_BUILD_TYPE=Release ;
           cmake ${{env.TFM_DIR}} -B ${{env.DEB_DIR}} -DCMAKE_BUILD_TYPE=Debug

    - name: Build on MacOS
      run: cmake --build ${{env.REL_DIR}} --config Release -j4 ;
           cmake --build ${{env.DEB_DIR}} --config Debug -j4

    - uses: actions/upload-artifact@v2
      with:
        name: compilation-for-macos
        path: |
          ${{env.REL_DIR}}/libtfm.so*
          ${{env.DEB_DIR}}/libtfmdebug.so*
